---
nav:
  - index.md

site_name: Proper Form
site_description: A not-terrible Python form library.
site_author: Juan-Pablo Scaletti
site_url: https://github.com/

repo_name: 
repo_url: https://github.com/
edit_uri: ""

theme:
  name: material
  custom_dir: material
  logo:
    icon: cloud_done
  palette:
    primary: red
    accent: pink

extra_css:
  - css/monokai.css
  - css/extra.css

# Customization
extra:
  # manifest: "manifest.webmanifest"
  social:
    - type: globe
      link: https://github.com/jpscaletti/proper-form
    - type: github-alt
      link: https://github.com/

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
      guess_lang: false
  - smarty
  - toc:
      permalink: "#"
  - markdown.extensions.tables
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tildegoogle_analytics:
  - UA-XXXXXXXX-X
  - auto