---
nav:
  - Welcome: index.md
  - crash.md
  - forms.md
  - fields.md
  - rendering.md
  - validators.md
  - formsets.md
  - orm.md
  - FAQ: faq.md

site_name: Proper Form
site_description: A not-terrible Python form library.
site_author: Juan-Pablo Scaletti
site_url: https://github.com/jpsca/proper-form

repo_name: jpsca/proper-form
repo_url: https://github.com/jpsca/proper-form
edit_uri: ""

theme:
  name: material
  features:
    - instant
  icon:
    logo: material/cloud
  palette:
    primary: red
    accent: pink
  language: en

extra_css:
  - css/colorful.css
  # - css/monokai.css
  - css/extra.css

# Customization
extra:
  # manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jpsca/proper-form

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      css_class: highlight
      guess_lang: false
  - smarty
  - toc:
      permalink: "#"
      toc_depth: 4
  - markdown.extensions.tables
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
